AllCops:
  DisabledByDefault: true

Layout:
  Enabled: True
Layout/EndOfLine:
  Enabled: false
Layout/LineLength:
  AutoCorrect: false
  Enabled: false
Layout/RescueEnsureAlignment:
  AutoCorrect: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/LineContinuationLeadingSpace: # new in 1.31
  Enabled: true
Layout/LineContinuationSpacing: # new in 1.31
  Enabled: true
Layout/LineEndStringConcatenationIndentation: # new in 1.18
  Enabled: true
Lint/DeprecatedClassMethods:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateHashKey:
  Enabled: true
Lint/DuplicateMethods:
  Enabled: true
Lint/InterpolationCheck:
  Enabled: true
Lint/LiteralAsCondition:
  Enabled: true
Lint/RedundantStringCoercion:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/UnderscorePrefixedVariableName:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Style/AndOr:
  Enabled: true
Style/Documentation:
  Exclude:
    - '**/tests/*.rb'
    - 'workflow/**/*.rb'
    - 'tasks.rb'
Style/DocumentationMethod:
  Exclude:
    - '**/tests/*.rb'
    - 'workflow/**/*.rb'
    - 'tasks.rb'
Style/FrozenStringLiteralComment:
  Enabled: true
Style/HashSyntax:
  Enabled: true
Style/Next:
  Enabled: true
Style/NilComparison:
  Enabled: true
Style/RedundantParentheses:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/ReturnNil:
  Enabled: true
Style/SelfAssignment:
  Enabled: true
Style/StringLiterals:
  Enabled: true
Style/StringLiteralsInInterpolation:
  Enabled: true