version: 2
jobs:
  build:
    docker:
      - image: nrel/openstudio:3.1.0-rc1
    steps:
      - checkout
      - run: 
          name: Install gems
          command: |
            rm -f Gemfile.lock && bundle install
      - run: 
          name: Run tests
          command: |
            bundle exec rake test_all
      - persist_to_workspace:
          root: workflow
          paths:
            - test_results/*
      - store_artifacts:
          path: workflow/test_results
          destination: results
  makeplots:
    docker:
      - image: continuumio/miniconda3
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/data
      - run:
          name: Install plotting packages
          command: |
            conda install -y bokeh pandas lxml
      - run:
          name: Plot comparison
          command: |
            python plots/make_comparison_plots.py plots/doe2_enduse_v8_4.csv /tmp/data/test_results/results.csv
      - run:
          name: Plot comparison w/ ERI setpoints
          command: |
            python plots/make_comparison_plots.py plots/doe2_enduse_v8_4_eri_setpoints.csv /tmp/data/test_results/results.csv
      - store_artifacts:
          path: plots/plots
          destination: plots

workflows:
  version: 2
  oshpxml:
    jobs:
      - build
      - makeplots:
          requires:
            - build