name: ci

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2

      - name: Install gems
        run: |
          rm -f Gemfile.lock && bundle install

      - name: Run tests
        run: |
          bundle exec rake test_all

      - name: Compare results
        run: |
          ruby workflow/compare.rb

      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          path: workflow/tests/results
          name: results

      - name: Store comparisons
        uses: actions/upload-artifact@v2
        with:
          path: workflow/tests/comparisons
          name: comparisons   
