name: Run Tests and Plot results
on: [push]
jobs:
  runtests:
    runs-on: ubuntu-latest
    container:
      image: nrel/openstudio:3.1.0
    steps:
      - uses: actions/checkout@v2
      - name: Install gems
        run: rm -f Gemfile.lock && bundle install
      - name: Run tests
        run: bundle exec rake test_all
